# Generated by Django 5.1.7 on 2025-05-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailApp', '0004_task_taskstatus_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskstatus',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Complete')], default=0),
        ),
    ]
